### PR TITLE
adding debian support

### PR DESCRIPTION
**Pull request by zoide**

### CODE REVIEW

**Comment by andyshinn** [comment]
Does this rely on https://github.com/puppetlabs/puppetlabs-apt? Just want to make sure so I can update the README also.

**Comment by zoide** [comment]
Yes, it does.

**Comment by andyshinn** [comment]
This pull request is pretty old and this is not something I can test (as I am not using Puppet or MegaRAID anymore). Is this project something you would be interested in taking under your user?

I'm doing some GitHub cleanup and want to delete or migrate this somewhere.

**Comment by zoide** [comment]
Hi there. Yes, I would gladly take the project over. Thanks.

**Comment by andyshinn** [comment]
:thumbsup:

**Pull request merged**
